name: Lint

on:
  push:
    branches: [$default-branch, $protected-branches]
  pull_request:
    branches: [$default-branch]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
